<!DOCTYPE html><html><head><meta name="generator" content="Hexo 3.8.0"><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport"><meta content="yes" name="apple-mobile-web-app-capable"><meta content="black-translucent" name="apple-mobile-web-app-status-bar-style"><meta content="telephone=no" name="format-detection"><meta name="description"><title>python try-except-finally, return and raise | I'm J2hongming</title><link rel="stylesheet" type="text/css" href="/css/normalize.css"><link rel="stylesheet" type="text/css" href="/css/highlight.css"><link rel="stylesheet" type="text/css" href="/css/very-simple.css"><link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css"><link rel="Shortcut Icon" type="image/x-icon" href="/favicon.ico"><link rel="alternate" type="application/atom+xml" href="/atom.xml"></head><body><!-- include the sidebar--><!-- include ./includes/sidebar.jade--><!-- Blog title and subtitle--><header><div class="container header"><a id="logo" href="/." class="title">I'm J2hongming</a><span class="subtitle">Appreciate, respect and accept it, don't take it for granted</span><label id="toggle-menu" for="menu" onclick><i class="fa fa-bars"></i></label></div></header><!-- use checkbox hack for toggle nav-bar on small screens--><input id="menu" type="checkbox"><!-- Navigation Links--><nav id="nav"><div class="container"><a href="/" class="sidebar-nav-item active">Home</a><a href="/archives" class="sidebar-nav-item">Archives</a><a href="/sitemap" class="sidebar-nav-item">SiteMap</a><a href="/experience" class="sidebar-nav-item">Experience</a><a href="/bookshelf" class="sidebar-nav-item">Bookshelf</a><a href="https://www.linkedin.com/in/j2hongming/" class="sidebar-nav-item">About</a></div></nav><div id="header-margin-bar"></div><!-- gallery that comes before the header--><div class="wrapper"><div class="container post-header"><h1>python try-except-finally, return and raise</h1></div></div><div class="wrapper"><div class="container meta"><div class="post-time">2021-11-25</div><div class="post-categories"><a class="post-category-link" href="/categories/software-development/">software_development</a></div><div class="post-tags"><a class="post-tag-link" href="/tags/exception/">exception</a>/<a class="post-tag-link" href="/tags/python/">python</a></div></div></div><article><div class="container post"><p>利用request module呼叫外部服務時透過raise_for_status處理HTTPError, 遇到某一種HTTP code時需要再raise一個自定義的Exception出去, 但發現沒有發揮作用</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    result = dict()</span><br><span class="line">    r = requests.get(<span class="string">'http://www.google.com/nothere'</span>)</span><br><span class="line">    r.raise_for_status()</span><br><span class="line"><span class="keyword">except</span> requests.exceptions.HTTPError <span class="keyword">as</span> err:</span><br><span class="line">    <span class="keyword">raise</span> MyCustomizedException(err)</span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="keyword">return</span> result</span><br></pre></td></tr></table></figure>

<p>先說結論, 因為finally內有return的語法, 所以MyCustomizedException不會被raise, python的官方文件說得很清楚</p>
<blockquote>
<p>If the finally clause executes a break, continue or return statement, exceptions are not re-raised.</p>
</blockquote>
<p>第二次遇到這種情況, 嘗到沒好好地看文件和紀錄的苦果, 決定記錄下來關於<code>try-except-finally</code>, <code>return</code> 和 <code>raise</code>的關係</p>
<p>文件中提到以下注意事項</p>
<ul>
<li>If an exception occurs during execution of the try clause, the exception may be handled by an except clause. If the exception is not handled by an except clause, the exception is re-raised after the finally clause has been executed.</li>
<li>An exception could occur during execution of an except or else clause. Again, the exception is re-raised after the finally clause has been executed.</li>
<li>If the finally clause executes a break, continue or return statement, exceptions are not re-raised.</li>
<li>If the try statement reaches a break, continue or return statement, the finally clause will execute just prior to the break, continue or return statement’s execution.</li>
<li>If a finally clause includes a return statement, the returned value will be the one from the finally clause’s return statement, not the value from the try clause’s return statement.</li>
</ul>
<p>沒有處理或處理過程中又發生其他Exception的時候, 一般來說會在finally block完成後re-raise </p>
<p>在finally block包含<code>break</code>, <code>continue</code> 或 <code>return</code> 語法時, 不會re-raise</p>
<h2 id="try-except-finally-and-return"><a href="#try-except-finally-and-return" class="headerlink" title="try-except-finally and return"></a>try-except-finally and return</h2><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span>:</span><br><span class="line">    <span class="comment"># &lt;= retrun here</span></span><br><span class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">    <span class="comment"># handle exception</span></span><br><span class="line"><span class="keyword">finally</span>:</span><br><span class="line">    <span class="comment"># &lt;= return here</span></span><br></pre></td></tr></table></figure>

<p>有三種狀況</p>
<ol>
<li>retrun in try</li>
<li>return in finally</li>
<li>return in both</li>
</ol>
<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 1. return in try</span></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">return_in_try_with_finally</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        print(<span class="string">'return in try with finally'</span>)</span><br><span class="line">        print(<span class="string">'try block'</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span></span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(<span class="string">'in exception block'</span>)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'finally block'</span>)</span><br><span class="line">        </span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    print(return_in_try_with_finally()</span><br><span class="line">          </span><br><span class="line"><span class="comment"># return in try with finally</span></span><br><span class="line"><span class="comment"># try block</span></span><br><span class="line"><span class="comment"># finally block</span></span><br><span class="line"><span class="comment"># 1</span></span><br></pre></td></tr></table></figure>

<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 2. return in finally</span></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">return_in_finally</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        print(<span class="string">'return in finally'</span>)</span><br><span class="line">        print(<span class="string">'try block'</span>)</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(<span class="string">'in exception block'</span>)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'finally block'</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    print(return_in_finally()</span><br><span class="line">    </span><br><span class="line"><span class="comment"># return in finally</span></span><br><span class="line"><span class="comment"># try block</span></span><br><span class="line"><span class="comment"># finally block</span></span><br><span class="line"><span class="comment"># 1</span></span><br></pre></td></tr></table></figure>

<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment"># 3. return in both</span></span><br><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">return_in_try_and_finally</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        print(<span class="string">'return in try and finally'</span>)</span><br><span class="line">        print(<span class="string">'try block'</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="number">1</span></span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(<span class="string">'in exception block'</span>)</span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'finally block'</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="number">3</span></span><br><span class="line">    </span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    print(return_in_try_and_finally()</span><br><span class="line">          </span><br><span class="line"><span class="comment"># return in try and finally</span></span><br><span class="line"><span class="comment"># try block</span></span><br><span class="line"><span class="comment"># finally block</span></span><br><span class="line"><span class="comment"># 3</span></span><br></pre></td></tr></table></figure>

<h2 id="try-except-finally-return-and-raise"><a href="#try-except-finally-return-and-raise" class="headerlink" title="try-except-finally, return and raise"></a>try-except-finally, return and raise</h2><figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">return_in_try_and_finally_and_no_raise</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        print(<span class="string">'return in try with finally and no re-raise'</span>)</span><br><span class="line">        print(<span class="string">'try block'</span>)</span><br><span class="line">        result = <span class="number">1</span> / <span class="number">0</span></span><br><span class="line">        <span class="keyword">return</span> result</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(<span class="string">'in exception block'</span>)</span><br><span class="line">        <span class="keyword">raise</span> <span class="comment"># &lt;= no effect because there is a return statement in finally</span></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'finally block'</span>)</span><br><span class="line">        <span class="keyword">return</span> <span class="number">3</span></span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    print(return_in_try_and_finally_and_no_raise()    </span><br><span class="line"></span><br><span class="line"><span class="comment"># return in try with finally and no re-raise</span></span><br><span class="line"><span class="comment"># try block</span></span><br><span class="line"><span class="comment"># in exception block</span></span><br><span class="line"><span class="comment"># finally block</span></span><br><span class="line"><span class="comment"># 3</span></span><br></pre></td></tr></table></figure>

<figure class="highlight python"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">def</span> <span class="title">return_in_try_with_finally_and_has_raise</span><span class="params">()</span>:</span></span><br><span class="line">    <span class="keyword">try</span>:</span><br><span class="line">        print(<span class="string">'return in try with finally and re-raise'</span>)</span><br><span class="line">        print(<span class="string">'try block'</span>)</span><br><span class="line">        result = <span class="number">1</span> / <span class="number">0</span></span><br><span class="line">        <span class="keyword">return</span> result</span><br><span class="line">    <span class="keyword">except</span> Exception <span class="keyword">as</span> e:</span><br><span class="line">        print(<span class="string">'in exception block'</span>)</span><br><span class="line">        <span class="keyword">raise</span></span><br><span class="line">    <span class="keyword">finally</span>:</span><br><span class="line">        print(<span class="string">'finally block'</span>)</span><br><span class="line"></span><br><span class="line"><span class="keyword">if</span> __name__ == <span class="string">'__main__'</span>:</span><br><span class="line">    print(return_in_try_with_finally_and_has_raise()  </span><br><span class="line">        </span><br><span class="line"><span class="comment"># Traceback (most recent call last):</span></span><br><span class="line"><span class="comment">#   File "/home/j2hongming/labs/2018-ithome-ironman-python/exception/finally_return.py", line 103, in &lt;module&gt;</span></span><br><span class="line"><span class="comment">#     print(return_in_try_with_finally_and_has_raise())</span></span><br><span class="line"><span class="comment">#   File "/home/j2hongming/labs/2018-ithome-ironman-python/exception/finally_return.py", line 72, in return_in_try_with_finally_and_has_raise</span></span><br><span class="line"><span class="comment">#     result = 1 / 0</span></span><br><span class="line"><span class="comment"># ZeroDivisionError: division by zero</span></span><br></pre></td></tr></table></figure>

<h2 id="reference"><a href="#reference" class="headerlink" title="reference"></a>reference</h2><ul>
<li><a href="https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions" target="_blank" rel="noopener">Defining Clean-up Actions</a></li>
<li><a href="https://stackoverflow.com/questions/19805654/python-try-finally-block-returns" target="_blank" rel="noopener">Python try finally block returns</a></li>
<li><a href="https://stackoverflow.com/questions/43830803/re-raising-the-exception-doesnt-work-with-finally-clause" target="_blank" rel="noopener">Re-raising the exception doesn’t work with “finally” clause</a></li>
</ul>
</div><!-- comment system--><div class="container"><hr><div id="disqus_thread"></div><script type="text/javascript">
var disqus_shortname = 'j2hongminggithubio';
var disqus_identifier = '2021/11/25/python-try-except-finally-return-raise/';
var disqus_title = 'python try-except-finally, return and raise';
var disqus_url = 'http://yoursite.com/2021/11/25/python-try-except-finally-return-raise/';
(function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">Blog comments powered by <span class="logo-disqus">Disqus</span></a></div></article><footer id="footer"><div class="container"><div class="bar"><div class="social"><a href="http://twitter.com/j2hongming" target="_blank"><i class="fa fa-twitter"></i></a><a href="https://github.com/j2hongming" target="_blank"><i class="fa fa-github"></i></a><a href="/atom.xml" target="_blank"><i class="fa fa-rss"></i></a></div><div class="footer">© 2022 <a href="/" rel="nofollow">J2hongming</a>. Powered by <a rel="nofollow" target="_blank" href="https://hexo.io">Hexo</a>. Theme <a target="_blank" href="https://github.com/lotabout/very-simple">very-simple</a>.</div></div></div></footer><link rel="stylesheet" type="text/css" href="//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.css"><script src="//cdn.bootcss.com/jquery/2.0.3/jquery.min.js"></script><script src="//cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js"></script><script>$(document).ready(function() {
    $(".fancybox").fancybox();
});
</script></body><script>(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
e=o.createElement(i);r=o.getElementsByTagName(i)[0];
e.src='//www.google-analytics.com/analytics.js';
r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
ga('create','UA-55818738-1');ga('send','pageview');</script></html>